NAME: 'SegNeuron'

MODEL:
  model_type: "default"
  pre_train: True
  # pretrain_path: '/data/wangfeiran/code/brainbow/segmentation/SegNeuron/Pretrain/models/2025-01-21--20-40-29_SegNeuron/model-050000.ckpt'
  # pretrain_path: '/data/wangfeiran/code/brainbow/segmentation/SegNeuron/models/SegNeuronModel.ckpt'
  pretrain_path: '/data/wangfeiran/code/brainbow/segmentation/SegNeuron/Train_and_Inference/models/2025-02-05--20-35-55_SegNeuron/model-028000.ckpt'
  continue_train: False
  continue_path: '/***/***'


TRAIN:
  resume: False
  if_valid: True
  cache_path: './caches/'
  save_path: './models/'
  pad: 0
  loss_func: 'BCELoss'
  opt_type: 'adam'
  display_freq: 100
  total_iters: 400000
  warmup_iters: 0
  base_lr: 0.01
  end_lr: 0.0001
  save_freq: 500
  valid_freq: 500
  decay_iters: 200000
  weight_decay: ~
  power: 1.5
  batch_size: 60
  num_workers: 60
  if_cuda: True
  random_seed: 666
  min_valid_iter: 10000
  freq_mix_prob: 0.25
  spa_mix_prob: 0.25

DATA:
  min_noise_std: 0.01
  max_noise_std: 0.2
  min_kernel_size: 3
  max_kernel_size: 9
  min_sigma: 0
  max_sigma: 2
  # data_folder: '/data/wangfeiran/code/brainbow/segmentation/SegNeuron/data/labeled'
  # data_folder_val: '/data/wangfeiran/code/brainbow/segmentation/SegNeuron/data/valid'
  # data_folder: '/data/wangfeiran/code/brainbow/segmentation/SegNeuron/data/brainbow'
  # data_folder_val: '/data/wangfeiran/code/brainbow/segmentation/SegNeuron/data/brainbow'

  # data_folder: '/data/wangfeiran/code/brainbow/segmentation/SegNeuron/data/'
  # data_folder_val: '/data/wangfeiran/code/brainbow/segmentation/SegNeuron/data/'
  # data_folder: '/data/wangfeiran/code/brainbow/segmentation/SegNeuron/data/czi'
  # data_folder_val: '/data/wangfeiran/code/brainbow/segmentation/SegNeuron/data/czi'
  start_slice: 0
  end_slice: 100
  val_start: 0
  val_end: 100
  predict_split: False
  if_ignore_bg: True

