name: segN
channels:
  - pytorch
  - funkelab
  - gurobi
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - ampl-asl=1.0.0
  - aom=3.5.0
  - blas=1.0
  - blosc=1.21.5
  - boost=1.78.0
  - boost-cpp=1.78.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.34.4
  - c-blosc2=2.12.0
  - ca-certificates=2025.4.26
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2025.4.26
  - cfitsio=3.470
  - charls=2.2.0
  - coin-or-cbc=2.10.12
  - coin-or-cgl=0.60.7
  - coin-or-clp=1.17.8
  - coin-or-osi=0.108.10
  - coin-or-utils=2.11.11
  - coincbc=2.10.12
  - colorama=0.4.6
  - contourpy=1.3.0
  - cppad=20240000.4
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.6.77
  - cuda-runtime=12.1.0
  - cuda-version=12.6
  - cyrus-sasl=2.1.27
  - dav1d=1.2.1
  - dbus=1.13.18
  - expat=2.6.4
  - ffmpeg=5.1.2
  - fftw=3.3.10
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.58.0
  - freetype=2.12.1
  - gettext=0.24.1
  - gettext-tools=0.24.1
  - giflib=5.2.2
  - glib=2.78.4
  - glib-tools=2.78.4
  - glpk=5.0
  - gmp=6.3.0
  - gmpy2=2.1.2
  - gnutls=3.7.9
  - gurobi=10.0.3
  - hdf5=1.14.0
  - icu=73.2
  - ilpy=0.4.0
  - imath=3.1.6
  - importlib-metadata=8.6.1
  - importlib-resources=6.5.2
  - importlib_resources=6.5.2
  - intel-openmp=2023.1.0
  - ipopt=3.14.16
  - jpeg=9e
  - jxrlib=1.1
  - keyutils=1.6.1
  - kiwisolver=1.4.7
  - krb5=1.20.1
  - lame=3.100
  - lazy-loader=0.4
  - lazy_loader=0.4
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lemon=1.3.1
  - lerc=3.0
  - libabseil=20250127.0
  - libaec=1.1.3
  - libasprintf=0.24.1
  - libasprintf-devel=0.24.1
  - libavif=0.11.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang13=14.0.6
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.11.1.6
  - libcups=2.3.3
  - libcurand=10.3.7.77
  - libcurl=8.12.1
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.17
  - libdrm=2.4.124
  - libedit=3.1.20240808
  - libev=4.33
  - libexpat=2.6.4
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgettextpo=0.24.1
  - libgettextpo-devel=0.24.1
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libglib=2.78.4
  - libgomp=14.2.0
  - libhwloc=2.10.0
  - libiconv=1.17
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm14=14.0.6
  - liblzma=5.6.3
  - liblzma-devel=5.6.3
  - libnghttp2=1.57.0
  - libnpp=12.0.2.50
  - libnsl=2.0.1
  - libntlm=1.8
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libopus=1.3.1
  - libpciaccess=0.18
  - libpng=1.6.39
  - libpq=17.4
  - libprotobuf=5.29.3
  - libscotch=7.0.4
  - libspral=2024.05.08
  - libsqlite=3.46.0
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libva=2.18.0
  - libvpx=1.11.0
  - libwebp-base=1.3.2
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.8.0
  - libxml2=2.13.5
  - libxslt=1.1.41
  - libzlib=1.2.13
  - libzopfli=1.0.3
  - llvm-openmp=15.0.7
  - lz4-c=1.9.4
  - matplotlib-base=3.9.4
  - metis=5.1.0
  - minizip=4.0.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.1.0
  - mpfr=4.2.1
  - mpmath=1.3.0
  - mumps-include=5.7.3
  - mumps-seq=5.7.3
  - munkres=1.1.4
  - mysql=8.4.0
  - ncurses=6.5
  - nettle=3.9.1
  - networkx=3.2.1
  - nifty=1.2.1
  - nspr=4.36
  - nss=3.100
  - openexr=3.1.5
  - openh264=2.3.1
  - openjpeg=2.5.2
  - openldap=2.6.5
  - openssl=3.5.0
  - p11-kit=0.24.1
  - pcre2=10.42
  - pip=24.2
  - pthread-stubs=0.4
  - pyside6=6.7.2
  - pysocks=1.7.1
  - python=3.9.21
  - python-dateutil=2.9.0.post0
  - python_abi=3.9
  - pytorch=2.1.1
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pywavelets=1.6.0
  - pyyaml=6.0.2
  - qhull=2020.2
  - qtbase=6.7.3
  - qtdeclarative=6.7.3
  - qtshadertools=6.7.3
  - qtsvg=6.7.3
  - qttools=6.7.3
  - qtwebchannel=6.7.3
  - qtwebengine=6.7.2
  - qtwebsockets=6.7.3
  - readline=8.2
  - requests=2.32.3
  - scikit-image=0.24.0
  - scikit-learn=1.6.1
  - scip=9.0.1
  - scipy=1.13.1
  - setuptools=75.1.0
  - six=1.17.0
  - snappy=1.1.10
  - sqlite=3.45.3
  - svt-av1=1.4.1
  - tbb=2021.12.0
  - threadpoolctl=3.6.0
  - tk=8.6.14
  - torchaudio=2.1.1
  - torchtriton=2.1.0
  - torchvision=0.16.1
  - tornado=6.5
  - tqdm=4.67.1
  - typing_extensions=4.12.2
  - unicodedata2=16.0.0
  - urllib3=2.3.0
  - vigra=1.11.1
  - wheel=0.44.0
  - x264=1!164.3095
  - x265=3.5
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-renderutil=0.3.10
  - xkeyboard-config=2.44
  - xorg-fixesproto=5.0
  - xorg-kbproto=1.0.7
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.6.3
  - xz-gpl-tools=5.6.3
  - xz-tools=5.6.3
  - yaml=0.2.5
  - zfp=1.0.1
  - zipp=3.21.0
  - zlib=1.2.13
  - zlib-ng=2.0.7
  - zstd=1.5.6
  - pip:
      - acvl-utils==0.2.1
      - addict==2.4.0
      - aicspylibczi==3.2.1
      - argparse==1.4.0
      - asciitree==0.3.3
      - asttokens==2.2.1
      - attrdict==2.0.1
      - batchgenerators==0.25.1
      - batchgeneratorsv2==0.2.1
      - beaker==1.13.0
      - beautifulsoup4==4.12.3
      - blinker==1.9.0
      - charset-normalizer==2.1.1
      - cloudpickle==2.2.1
      - cmake==3.31.4
      - connected-components-3d==3.22.0
      - cycler==0.11.0
      - decorator==5.1.1
      - dicom2nifti==2.5.1
      - dill==0.3.6
      - docstring-parser==0.16
      - dynamic-network-architectures==0.3.1
      - einops==0.8.0
      - elf==0.6.0
      - et-xmlfile==2.0.0
      - fasteners==0.19
      - fft-conv-pytorch==1.2.0
      - filelock==3.16.1
      - flask==2.3.2
      - formencode==2.1.0
      - fsspec==2024.12.0
      - future==1.0.0
      - greenlet==3.1.1
      - h5py==3.12.1
      - idna==3.10
      - imagecodecs==2024.12.30
      - imageio==2.37.0
      - itsdangerous==2.2.0
      - jinja2==3.1.5
      - joblib==1.4.2
      - linecache2==1.0.0
      - lit==18.1.8
      - llvmlite==0.43.0
      - magicgui==0.10.0
      - mako==1.3.8
      - markupsafe==3.0.2
      - matplotlib==3.7.1
      - mock==5.1.0
      - monai==1.1.0
      - nibabel==5.3.2
      - nose==1.3.7
      - numba==0.60.0
      - numcodecs==0.12.1
      - numpy==2.0.2
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu11==11.7.91
      - nvidia-nvtx-cu12==12.4.127
      - opencv-python==4.7.0.72
      - openpyxl==3.1.5
      - packaging==25.0
      - pandas==2.2.3
      - paste==3.10.1
      - pastedeploy==3.1.0
      - pastescript==3.7.0
      - pillow==11.3.0
      - protobuf==5.29.3
      - psygnal==0.11.1
      - pyconify==0.2
      - pygments==2.19.1
      - pylons==1.0.3
      - pyparsing==3.2.1
      - python-gdcm==3.0.24.1
      - python-graphviz==0.20.3
      - pytz==2024.2
      - qtpy==2.4.2
      - repoze-lru==0.7
      - routes==2.5.1
      - seaborn==0.13.2
      - simpleitk==2.4.1
      - simplejson==3.19.3
      - skan==0.12.2
      - soupsieve==2.6
      - sqlalchemy==2.0.37
      - superqt==0.7.1
      - sympy==1.13.1
      - tempita==0.6.0
      - tensorboardx==2.6.2.2
      - testify==0.11.3
      - tifffile==2024.8.30
      - toolz==1.0.0
      - traceback2==1.4.0
      - triton==3.1.0
      - tzdata==2024.2
      - unittest2==1.1.0
      - waitress==3.0.2
      - weberror==0.13.1
      - webhelpers==1.3
      - webob==1.8.9
      - webtest==3.0.3
      - werkzeug==3.1.3
      - yacs==0.1.8
      - zarr==2.18.2
prefix: /home/wangfeiran/anaconda3/envs/segN
